Objective:
Do work-flow in model

# pystdf

In [ ]:
!pip install pystdf

In [2]:
fname="/Users/jianlin/Documents/Project_STDF_wafermap/main_Lot_1_Wafer_1_Oct_13_09h33m41s_STDF"

In [3]:
import numpy as np
import pandas as pd
from pystdf.IO import Parser
from pystdf.Writers import TextWriter

class MemoryWriter:
    def __init__(self):
        self.data = []
    def after_send(self, dataSource, data):
        self.data.append(data)
    def write(self,line):
        self.data.append(line)
    def flush(self):
        pass # Do nothing

def ImportSTDF(fname):
    with open(fname,'rb') as fin:
        p = Parser(inp=fin)
        storage = MemoryWriter()
        p.addSink(storage)
        p.parse()
    return storage.data

def STDF2Text(fname,delimiter='|'):
    """ Convert STDF to a list of text representation
    """
    with open(fname,'rb') as fin:
        p = Parser(inp=fin)
        storage = MemoryWriter()
        p.addSink(TextWriter(storage,delimiter=delimiter))
        p.parse()
        return storage.data
    return None

def STDF2Dict(fname):
    """ Convert STDF to a list of dictionary objects
    """
    data = ImportSTDF(fname)
    data_out = []
    for datum in data:
        datum_out = {}
        RecType = datum[0].__class__.__name__.upper()
        datum_out['RecType'] = RecType
        for k,v in zip(datum[0].fieldMap,datum[1]):
            datum_out[k[0]] = v
        data_out.append(datum_out)
    return data_out

def STDF2DataFrame(fname):
    """ Convert STDF to a dictionary of DataFrame objects
    """
    data = ImportSTDF(fname)
    BigTable = {}
    for datum in data:
        RecType = datum[0].__class__.__name__.upper()
        if RecType not in BigTable.keys():
            BigTable[RecType] = {}
        Rec = BigTable[RecType]
        for k,v in zip(datum[0].fieldMap,datum[1]):
            if k[0] not in Rec.keys():
                Rec[k[0]] = []
            Rec[k[0]].append(v)
    for k,v in BigTable.items():
        BigTable[k] = pd.DataFrame(v)
    return BigTable

In [10]:
read_file = STDF2DataFrame(fname)
read_file

{'FAR':    CPU_TYPE  STDF_VER
 0         2         4,
 'ATR':       MOD_TIM                                           CMD_LINE
 0  1476351224  dataformatter tester config; Ver: SmarTest s/w...,
 'MIR':       SETUP_T     START_T  STAT_NUM MODE_COD RTST_COD PROT_COD  BURN_TIM  \
 0  1476351210  1476351224         1                 N              65535

   CMOD_COD LOT_ID PART_TYP  ... OPER_FRQ SPEC_NAM SPEC_VER FLOW_ID SETUP_ID  \
 0               1           ...

   DSGN_REV ENG_ID ROM_COD SERL_NUM SUPR_NAM
 0

 [1 rows x 38 columns],
 'SDR':    HEAD_NUM  SITE_GRP  SITE_CNT SITE_NUM HAND_TYP HAND_ID CARD_TYP CARD_ID  \
 0         1         2         1      [1]

   LOAD_TYP LOAD_ID DIB_TYP DIB_ID CABL_TYP CABL_ID CONT_TYP CONT_ID LASR_TYP  \
 0

   LASR_ID EXTR_TYP EXTR_ID
 0                           ,
 'PMR':    PMR_INDX  CHAN_TYP CHAN_NAM PHY_NAM LOG_NAM  HEAD_NUM  SITE_NUM
 0         1         1      Xin   10101       1         1         1
 1         2         2     Xout   10102       2         1         1
 2         3         0      VCC      11                 1         1
 3         1         1      Xin   10101       1         1         1
 4         2         2     Xout   10102       2         1         1
 5         3         0      VCC      11                 1         1,
 'WCR':    WAFR_SIZ  DIE_HT  DIE_WID  WF_UNITS WF_FLAT  CENTER_X  CENTER_Y POS_X POS_Y
 0       0.0     0.0      0.0         0            -32768    -32768            ,
 'WIR':    HEAD_NUM  SITE_GRP     START_T WAFER_ID
 0         1         2  1476351224         ,
 'PIR':     HEAD_NUM  SITE_NUM
 0          1         1
 1          1         1
 2          1         1
 3          1         1
 4          1         1
 5          1         1
 6          1         1
 7          1         1
 8          1         1
 9          1         1
 10         1         1
 11         1         1
 12         1         1,
 'PRR':     HEAD_NUM  SITE_NUM  PART_FLG  NUM_TEST  HARD_BIN  SOFT_BIN  X_COORD  \
 0          1         1         0         0         1         1       -5
 1          1         1         0         0         1         1       -1
 2          1         1         0         0         1         1        4
 3          1         1         0         0         1         1        6
 4          1         1         0         0         1         1        7
 5          1         1         0         0         1         1       -7
 6          1         1         0         0         1         1       -3
 7          1         1         0         0         1         1       -2
 8          1         1         0         0         1         1        3
 9          1         1         0         0         1         1        4
 10         1         1         0         0         1         1        6
 11         1         1         0         0         1         1       -6
 12         1         1         0         0         1         1       -4

     Y_COORD  TEST_T PART_ID PART_TXT PART_FIX
 0        -4     515       1    0.000       []
 1        -4       1       2    1.750       []
 2        -4       1       3    2.201       []
 3        -4       1       4    2.803       []
 4        -4       1       5    2.547       []
 5        -3       1       6    2.702       []
 6        -3       1       7    2.700       []
 7        -3       1       8    2.101       []
 8        -3       1       9    2.600       []
 9        -3       1      10    2.765       []
 10       -3       1      11    2.704       []
 11        0       1      12    2.802       []
 12        0       1      13    2.304       []  ,
 'WRR':    HEAD_NUM  SITE_GRP    FINISH_T  PART_CNT  RTST_CNT    ABRT_CNT  GOOD_CNT  \
 0         1         2  1476351281        13         0  4294967295        13

      FUNC_CNT WAFER_ID FABWF_ID FRAME_ID MASK_ID USR_DESC EXC_DESC
 0  4294967295                                                       ,
 'HBR':    HEAD_NUM  SITE_NUM  HBIN_NUM  HBIN_CNT HBIN_PF HBIN_NAM
 0         1         1         1        13       P     PASS
 1       255         0         1        13       P     PASS,
 'SBR':    HEAD_NUM  SITE_NUM  SBIN_NUM  SBIN_CNT SBIN_PF SBIN_NAM
 0         1         1         1        13       P     PASS
 1       255         0         1        13       P     PASS,
 'PCR':    HEAD_NUM  SITE_NUM  PART_CNT  RTST_CNT    ABRT_CNT  GOOD_CNT    FUNC_CNT
 0         1         1        13         0  4294967295        13  4294967295
 1       255         0        13         0  4294967295        13  4294967295,
 'MRR':      FINISH_T DISP_COD USR_DESC EXC_DESC
 0  1476351281                           }

# parse step by step

In [ ]:
#read and parsing
with open(fname,'rb') as fin:
    p = Parser(inp=fin)
    storage = MemoryWriter()
    p.addSink(storage)
    p.parse()
    for line in storage.data:
        print(line)

In [4]:
#to dataframe
data = ImportSTDF(fname)
for datum in data:
    if datum[0].__class__.__name__.upper()=='PRR':
        print(datum[0])

<pystdf.V4.Prr object at 0x7ff2683dc640>
<pystdf.V4.Prr object at 0x7ff2683dc640>
<pystdf.V4.Prr object at 0x7ff2683dc640>
<pystdf.V4.Prr object at 0x7ff2683dc640>
<pystdf.V4.Prr object at 0x7ff2683dc640>
<pystdf.V4.Prr object at 0x7ff2683dc640>
<pystdf.V4.Prr object at 0x7ff2683dc640>
<pystdf.V4.Prr object at 0x7ff2683dc640>
<pystdf.V4.Prr object at 0x7ff2683dc640>
<pystdf.V4.Prr object at 0x7ff2683dc640>
<pystdf.V4.Prr object at 0x7ff2683dc640>
<pystdf.V4.Prr object at 0x7ff2683dc640>
<pystdf.V4.Prr object at 0x7ff2683dc640>

In [47]:
# data processing & integrity checker
data = ImportSTDF(fname)
count=0
round_count=0
dict={}

for datum in data:
    if datum[0].__class__.__name__.upper()=='PRR':
        for k,v in zip(datum[0].fieldMap,datum[1]):
            #print(k[0],v)
            if k[0] not in dict.keys():
                dict[k[0]]=[v]
            else:
                dict[k[0]].append(v)
            count+=1
        round_count+=1
        
# integrity checking
print(count)
print(round_count)
print(len(dict.keys()))
if count/round_count == len(dict.keys()):
    print('data integrity is good')
else:
    print("there are some NULL Value!")

156
13
12
data integrity is good

In [50]:
# to dataframe
df = pd.DataFrame()
for key in dict.keys():
    df[key]=dict[key]
df

,HEAD_NUM,SITE_NUM,PART_FLG,NUM_TEST,HARD_BIN,SOFT_BIN,X_COORD,Y_COORD,TEST_T,PART_ID,PART_TXT,PART_FIX
0,1,1,0,0,1,1,-5,-4,515,1,0.000,[]
1,1,1,0,0,1,1,-1,-4,1,2,1.750,[]
2,1,1,0,0,1,1,4,-4,1,3,2.201,[]
3,1,1,0,0,1,1,6,-4,1,4,2.803,[]
4,1,1,0,0,1,1,7,-4,1,5,2.547,[]
5,1,1,0,0,1,1,-7,-3,1,6,2.702,[]
6,1,1,0,0,1,1,-3,-3,1,7,2.700,[]
7,1,1,0,0,1,1,-2,-3,1,8,2.101,[]
8,1,1,0,0,1,1,3,-3,1,9,2.600,[]
9,1,1,0,0,1,1,4,-3,1,10,2.765,[]
10,1,1,0,0,1,1,6,-3,1,11,2.704,[]
11,1,1,0,0,1,1,-6,0,1,12,2.802,[]
12,1,1,0,0,1,1,-4,0,1,13,2.304,[]